name: Replexica
description: Automated AI localization for dev teams.
author: Replexica

branding:
  icon: "aperture"
  color: "black"

runs:
  using: "docker"
  image: "action/Dockerfile"
  env:
    REPLEXICA_API_KEY: ${{ inputs.api-key }}
    REPLEXICA_PULL_REQUEST: ${{ inputs.pull-request }}
    REPLEXICA_COMMIT_MESSAGE: ${{ inputs.commit-message }}
    REPLEXICA_PULL_REQUEST_TITLE: ${{ inputs.pull-request-title }}
    REPLEXICA_WORKING_DIRECTORY: ${{ inputs.working-directory }}

inputs:
  api-key:
    description: "Replexica Platform API Key"
    required: true
  pull-request:
    description: "Create a pull request with the changes"
    default: false
    required: false
  commit-message:
    description: "Commit message"
    default: "feat: update translations via @replexica"
    required: false
  pull-request-title:
    description: "Pull request title"
    default: "feat: update translations via @replexica"
    required: false
  working-directory:
    description: "Working directory"
    default: "."
    required: false
