import type { Metadata } from "next";
import "./globals.css";
import loadIntl from "@/i18n/server";
import { IntlProvider } from "@/i18n/client";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: any) {
  const intl = await loadIntl(props.params.locale);

  return (
    <IntlProvider locale={intl.locale} messages={intl.messages}>
      <html lang={intl.locale}>
        <body className="">
          {props.children}
        </body>
      </html>
    </IntlProvider>
  );
}
